name: The Font
favicon: null
layout_spectrum: 0.41581627051346004
typography_spectrum: 0.14716993807815015
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005ec3'
    - '#0080ff'
    - '#008080'
    - '#006db6'
    - '#0000ff'
  brandStrength: 0.33277918212115765
  lightness: 0.04461295227520168
  saturation: 0.2555376132950187
  rhythmicContrast: 0.10424870578572154
purpose: []
